// The 7 particle-type configs ported verbatim from the nuke-theta demo
// (bundle.pretty.js:27852–28192). One entry per visual sub-component of
// the nuclear blast. Hex colour numbers, intervals, max-values and
// spline shapes are unchanged from the source.
// Source values stored as base-10 in the bundle:
//   FIRE  start=10959390 (0xA73A1E warm orange-red)  end=9643521 (0x932601 dark red-brown)
//   SMOKE start=6579300  (0x646464 medium grey)      end=8421504 (0x808080 lighter grey)
//   DEBRIS start=16741408 (0xFF7420 bright orange)   end=16777215 (0xFFFFFF white)
const FIRE_COLOURS = { start: 0xa73a1e, end: 0x932601 };
const SMOKE_COLOURS = { start: 0x646464, end: 0x808080 };
const DEBRIS_COLOURS = { start: 0xff7420, end: 0xffffff };
const NukeFire = {
    name: 'fire',
    enabled: true,
    alpha: 1,
    lifeTime: { minLife: 6, maxLife: 8 },
    blend: 0,
    particleType: 0,
    minRadius: 3.5,
    maxRadius: 5,
    dynamicSize: true,
    radiusMod: 0.2,
    sizeMod: 6,
    count: 2000,
    radiusModifier: 0.95,
    startColour: FIRE_COLOURS.start,
    endColour: FIRE_COLOURS.end,
    intervals: [0, 0.33, 0.66, 1],
    maxValues: { alpha: 1, speed: 1.5, size: 1.35 },
    spleens: {
        alpha: [0, 1, 1, 0],
        speed: [1, 0.66, 0.33, 0.06],
        size: [1, 0.3, 0.74, 0.148],
        colour: [
            { interval: 0, value: FIRE_COLOURS.start },
            { interval: 0.5, value: FIRE_COLOURS.end },
            { interval: 1, value: FIRE_COLOURS.end },
        ],
    },
};
const NukeSmoke = {
    name: 'smoke',
    enabled: true,
    alpha: 1,
    lifeTime: { minLife: 11, maxLife: 15 },
    blend: 1,
    particleType: 1,
    minRadius: 1.3,
    maxRadius: 3.44,
    dynamicSize: true,
    radiusMod: 0.2,
    sizeMod: 1.2,
    count: 3000,
    radiusModifier: 1.3,
    growingOnly: true,
    startColour: SMOKE_COLOURS.start,
    endColour: SMOKE_COLOURS.end,
    intervals: [0, 0.33, 0.66, 1],
    maxValues: { alpha: 1, speed: 2, size: 8 },
    spleens: {
        alpha: [0, 1, 1, 0],
        speed: [0.95, 1, 0.125, 0],
        size: [0.0375, 0.56, 0.78, 1],
        colour: [
            { interval: 0, value: SMOKE_COLOURS.start },
            { interval: 0.5, value: SMOKE_COLOURS.end },
            { interval: 1, value: SMOKE_COLOURS.end },
        ],
    },
};
const NukeMushroom = {
    name: 'mushroom',
    enabled: true,
    alpha: 1,
    lifeTime: { minLife: 10, maxLife: 14 },
    blend: 1,
    particleType: 3,
    minRadius: 1.21,
    maxRadius: 1.36,
    radiusMod: 1,
    sizeMod: 1,
    count: 500,
    radiusModifier: 1,
    minHeight: -2.5,
    maxHeight: 2,
    growingOnly: true,
    startColour: SMOKE_COLOURS.start,
    endColour: SMOKE_COLOURS.end,
    intervals: [0, 0.33, 0.66, 1],
    maxValues: { alpha: 1, speed: 2, size: 11, height: 16 },
    spleens: {
        alpha: [0, 0.5, 1, 0],
        speed: [0.55, 1, 0.08, 0],
        size: [0.2, 0.4, 0.85, 1],
        height: [0, 0.3, 0.65, 1],
        colour: [
            { interval: 0, value: SMOKE_COLOURS.start },
            { interval: 0.6, value: SMOKE_COLOURS.end },
            { interval: 1, value: SMOKE_COLOURS.end },
        ],
    },
};
const NukeMushroomFire = {
    name: 'mushroomFire',
    enabled: true,
    alpha: 1,
    lifeTime: { minLife: 5, maxLife: 6 },
    blend: 0,
    particleType: 4,
    minRadius: 0.8,
    maxRadius: 1.75,
    dynamicSize: true,
    radiusMod: 1,
    sizeMod: 2,
    count: 400,
    radiusModifier: 0.5,
    minHeight: -2,
    maxHeight: 2,
    startColour: FIRE_COLOURS.start,
    endColour: FIRE_COLOURS.end,
    intervals: [0, 0.33, 0.66, 1],
    maxValues: { alpha: 1, speed: 2, size: 5, height: 7 },
    spleens: {
        alpha: [0, 1, 1, 0],
        speed: [0.55, 1, 0.08, 0],
        size: [0.3, 0.4, 0.7, 1],
        height: [0.0714, 0.38, 0.689, 1],
        colour: [
            { interval: 0, value: FIRE_COLOURS.start },
            { interval: 0.5, value: FIRE_COLOURS.end },
            { interval: 1, value: FIRE_COLOURS.end },
        ],
    },
};
const NukeColumnFire = {
    name: 'columnFire',
    enabled: true,
    alpha: 1,
    lifeTime: { minLife: 6, maxLife: 8.5 },
    blend: 0,
    particleType: 5,
    minRadius: 2,
    maxRadius: 4,
    dynamicSize: true,
    radiusMod: 0.2,
    sizeMod: 3,
    count: 250,
    radiusModifier: 2.5,
    minHeight: -5,
    maxHeight: 1,
    vertical: true,
    startColour: FIRE_COLOURS.start,
    endColour: FIRE_COLOURS.end,
    intervals: [0, 0.33, 0.66, 1],
    maxValues: { alpha: 1, speed: 2, size: 3, height: 5 },
    spleens: {
        alpha: [0, 1, 1, 0],
        speed: [0.55, 1, 0.08, 0],
        size: [0, 0.85, 1, 1],
        height: [0, 0.33, 0.66, 1],
        colour: [
            { interval: 0, value: FIRE_COLOURS.start },
            { interval: 0.5, value: FIRE_COLOURS.end },
            { interval: 1, value: FIRE_COLOURS.end },
        ],
    },
};
const NukeColumnSmoke = {
    name: 'columnSmoke',
    enabled: true,
    alpha: 1,
    lifeTime: { minLife: 11, maxLife: 15 },
    blend: 1,
    particleType: 6,
    minRadius: 0.42,
    maxRadius: 0.8,
    dynamicSize: true,
    radiusMod: 0.2,
    sizeMod: 3,
    count: 50,
    radiusModifier: 0.335,
    minHeight: -5,
    maxHeight: 1,
    vertical: true,
    startColour: SMOKE_COLOURS.start,
    endColour: SMOKE_COLOURS.end,
    intervals: [0, 0.33, 0.66, 1],
    maxValues: { alpha: 1, speed: 2, size: 3, height: 10 },
    spleens: {
        alpha: [0, 1, 1, 0],
        speed: [0.55, 1, 0.08, 0],
        size: [0, 0.85, 1, 1],
        height: [0, 0.33, 0.66, 1],
        colour: [
            { interval: 0, value: SMOKE_COLOURS.start },
            { interval: 0.5, value: SMOKE_COLOURS.end },
            { interval: 1, value: SMOKE_COLOURS.end },
        ],
    },
};
const NukeDebris = {
    name: 'debris',
    enabled: true,
    alpha: 1,
    lifeTime: { minLife: 2, maxLife: 3 },
    blend: 1,
    particleType: 2,
    minRadius: 1,
    maxRadius: 3,
    dynamicSize: false,
    sizeMod: 0.1,
    count: 500,
    minHeight: -1,
    maxHeight: 1,
    radiusModifier: 1,
    minSize: 0,
    maxSize: 3,
    startColour: DEBRIS_COLOURS.start,
    endColour: DEBRIS_COLOURS.end,
    intervals: [0, 0.33, 0.66, 1],
    maxValues: { alpha: 1, speed: 9, size: 1, height: 1.05 },
    spleens: {
        alpha: [0, 1, 1, 0],
        speed: [1, 0.444, 0.166, 0.033],
        size: [1, 0.832, 0.66, 0.5],
        height: [0, 0.65, 1, 0],
        colour: [
            { interval: 0, value: DEBRIS_COLOURS.start },
            { interval: 0.5, value: DEBRIS_COLOURS.end },
            { interval: 1, value: DEBRIS_COLOURS.end },
        ],
    },
};
// Source ordering from bundle.pretty.js:28205
export const PARTICLES_TO_GENERATE = [
    NukeFire,
    NukeSmoke,
    NukeMushroom,
    NukeMushroomFire,
    NukeColumnFire,
    NukeColumnSmoke,
    NukeDebris,
];
